Repository GTNewHorizons/GTNH-Intergalactic, pull requests merged in 2025-01, with the labels that each got.

#93 Clean up code before merge
  src/main/java/com/gtnewhorizons/gtnhintergalactic/GTNHIntergalactic.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/gui/IG_UITextures.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/loader/MachineLoader.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/proxy/ClientProxy.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/proxy/CommonProxy.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/GT_MetaTileEntity_EnhancedMultiBlockBase_EM.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/TileEntityDysonSwarm.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/elevator/TileEntitySpaceElevator.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleBase.java
Labels: :construction: Testing on Zeta

#101 Add tier check to space assembler
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleAssembler.java
Labels: safe for stable

#103 Update asteroid outpost to gt solars
  src/main/java/com/gtnewhorizons/gtnhintergalactic/recipe/SpaceProjectRegistration.java
Labels: enhancement

#105 Fix mining module drone stocking exploit
  src/main/java/com/gtnewhorizons/gtnhintergalactic/tile/multi/elevatormodules/TileEntityModuleMiner.java
  src/main/resources/assets/gtnhintergalactic/lang/en_US.lang
Labels: bug

#107 Fix dyson casings not using proper meta methods
  src/main/java/com/gtnewhorizons/gtnhintergalactic/block/BlockCasingDysonSwarm.java
  src/main/java/com/gtnewhorizons/gtnhintergalactic/item/ItemCasingDysonSwarm.java
Labels: bug
